import { type NextPage } from "next";
import Head from "next/head";
import { Header } from "~/components/Header";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex min-h-screen bg-neutral-900">
        <Header />
        <main></main>
      </div>
    </>
  );
};

export default Home;
