import { useUser } from "@clerk/nextjs";
import { useAtom } from "jotai";
import { type NextPage } from "next";
import Head from "next/head";
import Header from "~/components/Header";
import Sidebar, { searchParamsAtom } from "~/components/Sidebar";
import { api } from "~/utils/api";

const Home: NextPage = () => {
  const { user } = useUser();
  const [searchParams] = useAtom(searchParamsAtom)

  const { data: goals } = api.goal.getAll.useQuery(searchParams, {
    enabled: !!user,
  });

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex min-h-screen flex-col bg-neutral-900">
        <Header />
        <main className="flex gap-8 p-12">
          <Sidebar />
          <div>
            <ul className="flex flex-wrap gap-4">
              {goals?.map((goal) => (
                <li
                  key={goal.id}
                  className="flex w-[250px] flex-col gap-4 rounded-md bg-neutral-800 p-8"
                >
                  <span className="text-neutral-300">{goal.title}</span>
                  <span className="text-neutral-300">{goal.description}</span>
                  <span className="text-neutral-300">
                    Priority: {goal.priority}
                  </span>
                  <span className="text-neutral-300">
                    Deadline: {goal.deadline?.toDateString()}
                  </span>
                  <span className="text-neutral-300">
                    isPublic: {String(goal.isPublic)}
                  </span>
                </li>
              ))}
            </ul>
          </div>
        </main>
      </div>
    </>
  );
};

export default Home;
